import { IAzureToken } from "./IAzureToken";

/** An abstraction around the Azure authentication process designed to enable mocking and unit test scenarios. */
export interface IAzureAuthenticator {

    /** Gets an authentication token for a service principal.
    * @param tenant The name of the Azure AD instance where the principal resides.
    * @param appId A GUID representing the ID of the principal, also known as ClientID.
    * @param appKey A shared secret generated by Azure AD for the principal.
    */
    getSPTokenCredentials(tenant: string, appId: string, appKey: string) : Promise<IAzureToken>;
}